import { useEffect } from "react";
import { siteConfig } from "./config/site";

interface SEOHeadProps {
  title: string;
  description: string;
  path: string;
  image?: string;
  type?: "website" | "article" | "product";
  schema?: Record<string, unknown> | Record<string, unknown>[];
  /**
   * Optional robots directive (e.g. "noindex, nofollow" or "index,follow").
   * Defaults to `index,follow` when omitted.
   */
  robots?: string;
}

/**
 * Internal helper that creates or updates head meta tags in-place.
 */
function setMeta(name: string, content: string, property = false) {
  const selector = property ? `meta[property='${name}']` : `meta[name='${name}']`;
  let tag = document.head.querySelector(selector) as HTMLMetaElement | null;
  if (!tag) {
    tag = document.createElement("meta");
    if (property) tag.setAttribute("property", name);
    else tag.setAttribute("name", name);
    document.head.appendChild(tag);
  }
  tag.setAttribute("content", content);
}

/**
 * Route-level SEO manager.
 *
 * Responsibilities:
 * - Update document title and meta descriptions.
 * - Set Open Graph and Twitter cards for social sharing.
 * - Maintain canonical URL tags.
 * - Inject JSON-LD schema for organization, product, breadcrumb, and article
 *   markup generated by pages.
 *
 * This centralizes metadata behavior so each page only provides content.
 */
export function SEOHead({ title, description, path, image, type = "website", schema, robots }: SEOHeadProps) {
  useEffect(() => {
    const canonical = `${siteConfig.domain}${path}`;
    document.title = title;

    // Robots directive (index by default)
    setMeta("robots", robots ?? "index,follow");

    setMeta("description", description);
    setMeta("keywords", siteConfig.keywords.join(", "));
    setMeta("og:type", type, true);
    setMeta("og:title", title, true);
    setMeta("og:description", description, true);
    setMeta("og:url", canonical, true);
    setMeta("og:image", image ?? siteConfig.images.hero, true);
    setMeta("twitter:card", "summary_large_image");
    setMeta("twitter:title", title);
    setMeta("twitter:description", description);
    setMeta("twitter:image", image ?? siteConfig.images.hero);

    let link = document.head.querySelector("link[rel='canonical']") as HTMLLinkElement | null;
    if (!link) {
      link = document.createElement("link");
      link.rel = "canonical";
      document.head.appendChild(link);
    }
    link.href = canonical;

    const previousScripts = document.head.querySelectorAll("script[data-seo-schema='true']");
    previousScripts.forEach((script) => script.remove());
    if (schema) {
      const script = document.createElement("script");
      script.type = "application/ld+json";
      script.dataset.seoSchema = "true";
      script.text = JSON.stringify(schema);
      document.head.appendChild(script);
    }
  }, [description, image, path, schema, title, robots]);

  return null;
}
